
FROM eclipse-temurin:17-jdk-jammy

# Install curl for health checks
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY target/library-management-system-1.0.0.jar  app.jar

# Simple entrypoint
ENTRYPOINT ["java", "-jar", "/app/app.jar"]