FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY target/library-management-system-1.0.0.jar app.jar



# Use an entrypoint script to handle dependencies
RUN apt-get update && apt-get install -y mongodb-mongosh curl
ENTRYPOINT ["/bin/sh", "-c", "exec java -jar /app/app.jar"]